// let a = 50
// let b = a
// sb = 60

// console.log(b);

// let obj1 = { x: 100, y: 400 }
// let obj2 = obj1
// obj2.x=500

// console.log(obj1);
// console.log(obj2);

// positive number

// let a = 50
// if (a>0){
//     console.log(a+" is a positive number");
// }


// find positive and negative Number

// let a = 100

// if (a>0){
//     console.log(a+" is a positive number");
// }
// else if(a<0){
//     console.log(a+ " is a negative number");
// }
// else if(a==0){
//     console.log("it is a zero");
// }

// else {console.log("it is not a number");

// }


// let money = 5000

// if (money >= 10000){
//     console.log("we can go to Goa");
//     money = 2000
// }
// else if (money <=10000){
//     console.log("i will save money");
//     money = 60000
// }
// console.log(money);

// let frnds = 2;

// if (frnds ==4){
//     console.log("we can play BGMI");

// }
// else {
//     let frnd1 = "shubham";
//     let frnd2 = "savita";
// }
// console.log(frnd1)

// let frnds = 1;

// if (frnds ==4){
//     console.log("we can play BGMI");

// }
// else {
//     var frnd1 = "shubham";
//     var frnd2 = "savita";
// }
// console.log(frnd1)


// let x = 50

// var y = 80 

// if (x){
//     let x=60
//     var y = 5000
//     console.log(x);
//     console.log(y);
// }

// console.log(x);
// console.log(y);

// let x = 50

// var y = 80 

// if (x){
//     x =60
//     y = 5000
//     console.log(x);
//     console.log(y);
// }

// console.log(x);
// console.log(y);


let x = 50

var y = 80 
let z = NaN

if (z){
    x =60
    y = 5000
    console.log(x);
    console.log(y);
}

console.log(x);
console.log(y);


